#!/bin/bash

set -e
checkExitCode() {
if [ $? -ne 0 ]; then
    echo "Error"
    exit 1;
fi
}

BASEDIR=`dirname $0`

. $BASEDIR/io.sh 1 3 2 "$@"

set -x
echo "hola"
docker run \
    -v --rm \
    -v wings_dev_wings_data:/opt/wings mosorio/bikes_rent \
    python script.py \
        --inputs $INPUTS1 \
		--pi_value $OUTPUTS1 \
		--summary $OUTPUTS2 \
    	--variables $PARAMS1 $PARAMS2 $PARAMS3
checkExitCode
